### ISSUE TITLE
导航栏图标重复

### ISSUE THREAD

**Issue by SiyerBOBO** [linuxdeepin/deepin-log-viewer#2]
深度日志收集工具：deepin-log-viewer
出错的代码文件：deepin-log-viewer/application/loglistview.cpp
错误行：353行、364行
BUG描述：软件主界面“启动事件”图标与“开关机事件”图标重复
BUG分析：深度日志收集工具主界面左侧导航按钮（共7枚），由14份*.svg图片作为图标，其中start.svg被调用两次，而kwin.svg未被正确调用，进而导致图标重复。
BUG修复建议：开关机事件行（）图标修改为kwin.svg，检查365-367行代码执行情况。
`
if (item) {
    setCustomFont(item);
    if (item->data(ITEM_DATE_ROLE).toString() == JOUR_TREE_DATA) {
        _itemIcon = icon + "system.svg";
    } else if (item->data(ITEM_DATE_ROLE).toString() == KERN_TREE_DATA) {
        _itemIcon = icon + "core.svg";

    } else if (item->data(ITEM_DATE_ROLE).toString() == BOOT_TREE_DATA) {
        _itemIcon = icon + "start.svg";

    } else if (item->data(ITEM_DATE_ROLE).toString() == DPKG_TREE_DATA) {
        _itemIcon = icon + "d.svg";

    } else if (item->data(ITEM_DATE_ROLE).toString() == XORG_TREE_DATA) {
        _itemIcon = icon + "x.svg";

    } else if (item->data(ITEM_DATE_ROLE).toString() == APP_TREE_DATA) {
        _itemIcon = icon + "application.svg";
    } else if (item->data(ITEM_DATE_ROLE).toString() == LAST_TREE_DATA) {
        _itemIcon = icon + "start.svg";
    } else if (item->data(ITEM_DATE_ROLE).toString() == KWIN_TREE_DATA) {
        _itemIcon = icon + "kwin.svg";
    }
    if (currentItem != nullptr && item == currentItem) {
        _itemIcon.replace(".svg", "_checked.svg");
    }
    item->setIcon(QIcon(_itemIcon));
    item->setData(_itemIcon, ICON_DATA);
}`

**Comment by z966768** [comment]
已收集,谢谢反馈

**Comment by z966768** [comment]
新版已修复
